version: '3.8'

services:
  command-predictor-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./app/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1